version: '3.9'

services:
  web:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: django-web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./backend/.env

  worker:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: celery-worker
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - web
      - redis
    env_file:
      - ./backend/.env

  beat:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: celery-beat
    command: celery -A core beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - worker
      - redis
    env_file:
      - ./backend/.env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
