web: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 3
worker: celery -A core worker --loglevel=info
beat: celery -A core beat --loglevel=info
flower: celery -A core flower --port=5555 --broker=redis://localhost:6379/0