from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import OrderViewSet, OrderItemViewSet

# DefaultRouter is used to automatically generate URLs for the viewsets.
router = DefaultRouter()

# Register the OrderItemViewSet with the 'items' prefix. This will create URLs for actions related to order items.
router.register(r'items', OrderItemViewSet)

# Register the OrderViewSet with the base URL. This will create URLs for actions related to orders.
router.register(r'', OrderViewSet)

urlpatterns = [
    # This includes all the URLs generated by the router for both viewsets.
    path('', include(router.urls)),
]
