from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import FeedbackViewSet


# Initialize the DefaultRouter
# The DefaultRouter automatically creates the URL routing for the viewset
router = DefaultRouter()
router.register(r'', FeedbackViewSet)  # Register the FeedbackViewSet with the router

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),  # Path for the feedback API
]
