# Generated by Django 5.2 on 2025-05-05 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_orders', models.PositiveIntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('most_sold_item', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
