version: '3.13'
services:
  backend:
    build: ../backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../backend:/app
    env_file:
      - ../backend/.env
    depends_on:
      - db
    expose:
      - 8000

  frontend:
    build: ../frontend
    volumes:
      - ../frontend/build:/usr/share/nginx/html
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html
      - ../backend/static:/app/static
      - ../backend/media:/app/media
    depends_on:
      - frontend
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpass
      POSTGRES_DB: yourdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
