from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    CustomUserViewSet, 
    SuperAdminViewSet, 
    StaffViewSet, 
    RegisterView, 
    LoginView, 
    LogoutView
)

from django.urls import path

# Create a DefaultRouter instance to automatically generate URL routes for viewsets
router = DefaultRouter()

# Register viewsets with specific basename to handle different user roles
router.register(r"all", CustomUserViewSet, basename="custom-users")  # Viewset for all users
router.register(r"superadmins", SuperAdminViewSet, basename="superadmins")  # Viewset for superadmins
router.register(r"staff", StaffViewSet, basename="staff")  # Viewset for staff users

# Define the main urlpatterns list, including routes for the viewsets registered above
urlpatterns = [
    path("", include(router.urls)),  # Includes all the viewsets automatically generated by the router
]

# Add URL routes for user registration, login, and logout views
urlpatterns += [
    path("register/", RegisterView.as_view(), name="register"),  # Endpoint for user registration
    path("login/", LoginView.as_view(), name="login"),  # Endpoint for user login
    path("logout/", LogoutView.as_view(), name="logout"),  # Endpoint for user logout
]
