from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TableViewSet


# Initialize a DefaultRouter which will automatically generate URLs for our viewsets
router = DefaultRouter()

# Register the 'TableViewSet' viewset to the router.
# The first argument is the URL prefix, and the second argument is the viewset class.
router.register(r'', TableViewSet)

urlpatterns = [
    # Include the URLs generated by the router into our URL configuration
    # This will automatically add routes like '/tables/', '/tables/{id}/', etc.
    path('', include(router.urls)),
]
